### ISSUE TITLE
Mismatched index.js

### ISSUE THREAD

**Issue by mbkulik** [PencilCode/jsonql#1]
It looks like index.js was included from another project (seedrandom? xor?)

The following simple example fails for me (jsonql was installed via npm)

``` javascript
var jsonql = require('jsonql');
```

```
module.js:338
    throw err;
          ^
Error: Cannot find module './xor/xor128'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous
(/home/mbk/projects/pencilcode/microdatabase/node_modules/jsonql/index.js:74:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

If I change "main" in package.json

from

```
"main" : "index.js"
```

to

```
"main" : "src/jsonql.js"
```

seems to fix the issue ( I am able to query JSON objects), but I am not sure if it is the correct solution

**Comment by davidbau** [comment]
Thanks!  Yes, was a leftover index.js - fixed!
